// /**
//  * NE3XA Laptop Catalogue
//  * Realistic product data for the store
//  */

// window.NE3XA = window.NE3XA || {};

// window.NE3XA.products = [
//   {
//     id: 'lp-001',
//     name: 'NE3XA ProBook 14',
//     brand: 'NE3XA',
//     category: 'business',
//     processor: 'Intel Core i5-1335U',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '14" FHD IPS',
//     os: 'Windows 11 Pro',
//     price: 899,
//     stock: 12,
//     image: 'images/laptop-1.svg',
//     description: 'Reliable business laptop built for everyday productivity. Lightweight chassis, full-day battery and enterprise-grade security features.',
//     tags: ['business', 'office', 'portable']
//   },
//   {
//     id: 'lp-002',
//     name: 'Dell Latitude 5440',
//     brand: 'Dell',
//     category: 'business',
//     processor: 'Intel Core i7-1355U',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '14" FHD',
//     os: 'Windows 11 Pro',
//     price: 1099,
//     stock: 8,
//     image: 'images/laptop-2.svg',
//     description: 'Dell Latitude series for professionals who need durability and manageability. Excellent keyboard and long battery life.',
//     tags: ['business', 'dell', 'enterprise']
//   },
//   {
//     id: 'lp-003',
//     name: 'HP EliteBook 840 G10',
//     brand: 'HP',
//     category: 'business',
//     processor: 'Intel Core i5-1335U',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '14" WUXGA',
//     os: 'Windows 11 Pro',
//     price: 1049,
//     stock: 6,
//     image: 'images/laptop-3.svg',
//     description: 'Premium HP business notebook with strong security and collaboration features. Ideal for hybrid work.',
//     tags: ['business', 'hp', 'premium']
//   },
//   {
//     id: 'lp-004',
//     name: 'Lenovo ThinkPad E14 Gen 5',
//     brand: 'Lenovo',
//     category: 'business',
//     processor: 'AMD Ryzen 5 7530U',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '14" FHD',
//     os: 'Windows 11 Pro',
//     price: 849,
//     stock: 15,
//     image: 'images/laptop-4.svg',
//     description: 'Classic ThinkPad reliability in a more accessible package. Great keyboard and solid build quality.',
//     tags: ['business', 'lenovo', 'thinkpad']
//   },
//   {
//     id: 'lp-005',
//     name: 'NE3XA Student 15',
//     brand: 'NE3XA',
//     category: 'student',
//     processor: 'Intel Core i3-1215U',
//     ram: '8GB',
//     storage: '256GB SSD',
//     display: '15.6" FHD',
//     os: 'Windows 11 Home',
//     price: 499,
//     stock: 22,
//     image: 'images/laptop-5.svg',
//     description: 'Affordable laptop designed for students. Handles coursework, research and light creative work without breaking the budget.',
//     tags: ['student', 'budget', 'school']
//   },
//   {
//     id: 'lp-006',
//     name: 'Acer Aspire 5',
//     brand: 'Acer',
//     category: 'student',
//     processor: 'AMD Ryzen 5 7520U',
//     ram: '8GB',
//     storage: '512GB SSD',
//     display: '15.6" FHD',
//     os: 'Windows 11 Home',
//     price: 549,
//     stock: 18,
//     image: 'images/laptop-6.svg',
//     description: 'Popular student choice with solid performance for coding, documents and online learning platforms.',
//     tags: ['student', 'acer', 'coding']
//   },
//   {
//     id: 'lp-007',
//     name: 'HP Pavilion 15',
//     brand: 'HP',
//     category: 'student',
//     processor: 'Intel Core i5-1235U',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '15.6" FHD',
//     os: 'Windows 11 Home',
//     price: 699,
//     stock: 14,
//     image: 'images/laptop-7.svg',
//     description: 'Balanced student laptop with enough power for multitasking and occasional media projects.',
//     tags: ['student', 'hp', 'multimedia']
//   },
//   {
//     id: 'lp-008',
//     name: 'NE3XA DevBook 16',
//     brand: 'NE3XA',
//     category: 'developer',
//     processor: 'Intel Core i7-13700H',
//     ram: '32GB',
//     storage: '1TB SSD',
//     display: '16" QHD 165Hz',
//     os: 'Windows 11 Pro / Ubuntu option',
//     price: 1499,
//     stock: 7,
//     image: 'images/laptop-8.svg',
//     description: 'Built for developers. High core count, abundant RAM and fast storage for containers, compilers and large projects.',
//     tags: ['developer', 'coding', 'performance']
//   },
//   {
//     id: 'lp-009',
//     name: 'ASUS Vivobook Pro 16',
//     brand: 'ASUS',
//     category: 'developer',
//     processor: 'AMD Ryzen 7 7735HS',
//     ram: '16GB',
//     storage: '1TB SSD',
//     display: '16" OLED 3.2K',
//     os: 'Windows 11 Home',
//     price: 1299,
//     stock: 5,
//     image: 'images/laptop-9.svg',
//     description: 'Excellent display and strong multi-core performance. Suitable for development and light design work.',
//     tags: ['developer', 'asus', 'oled']
//   },
//   {
//     id: 'lp-010',
//     name: 'Lenovo Legion 5',
//     brand: 'Lenovo',
//     category: 'gaming',
//     processor: 'AMD Ryzen 7 7735HS',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '15.6" FHD 165Hz',
//     os: 'Windows 11 Home',
//     price: 1199,
//     stock: 9,
//     image: 'images/laptop-10.svg',
//     description: 'Capable gaming laptop that also works well for creative workloads and heavier development tasks.',
//     tags: ['gaming', 'lenovo', 'performance']
//   },
//   {
//     id: 'lp-011',
//     name: 'Dell G15',
//     brand: 'Dell',
//     category: 'gaming',
//     processor: 'Intel Core i7-13650HX',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '15.6" FHD 165Hz',
//     os: 'Windows 11 Home',
//     price: 1249,
//     stock: 4,
//     image: 'images/laptop-11.svg',
//     description: 'Strong gaming performance with discrete graphics. Suitable for students and professionals who also game.',
//     tags: ['gaming', 'dell']
//   },
//   {
//     id: 'lp-012',
//     name: 'NE3XA Budget 14',
//     brand: 'NE3XA',
//     category: 'budget',
//     processor: 'Intel Celeron N4500',
//     ram: '8GB',
//     storage: '256GB SSD',
//     display: '14" HD',
//     os: 'Windows 11 Home in S mode',
//     price: 349,
//     stock: 30,
//     image: 'images/laptop-12.svg',
//     description: 'Entry-level laptop for basic office work, browsing and online classes. Best value for simple needs.',
//     tags: ['budget', 'entry', 'school']
//   },
//   {
//     id: 'lp-013',
//     name: 'HP 255 G9',
//     brand: 'HP',
//     category: 'budget',
//     processor: 'AMD Ryzen 3 5425U',
//     ram: '8GB',
//     storage: '256GB SSD',
//     display: '15.6" FHD',
//     os: 'Windows 11 Home',
//     price: 429,
//     stock: 20,
//     image: 'images/laptop-13.svg',
//     description: 'Affordable HP notebook with better processor than typical budget models. Good for everyday tasks.',
//     tags: ['budget', 'hp']
//   },
//   {
//     id: 'lp-014',
//     name: 'MacBook Air 13 M2',
//     brand: 'Apple',
//     category: 'developer',
//     processor: 'Apple M2',
//     ram: '16GB',
//     storage: '512GB SSD',
//     display: '13.6" Liquid Retina',
//     os: 'macOS',
//     price: 1499,
//     stock: 6,
//     image: 'images/laptop-14.svg',
//     description: 'Lightweight, silent and efficient. Popular among developers who prefer macOS and long battery life.',
//     tags: ['developer', 'apple', 'macbook']
//   },
//   {
//     id: 'lp-015',
//     name: 'ASUS ROG Zephyrus G14',
//     brand: 'ASUS',
//     category: 'gaming',
//     processor: 'AMD Ryzen 9 7940HS',
//     ram: '32GB',
//     storage: '1TB SSD',
//     display: '14" QHD 165Hz',
//     os: 'Windows 11 Home',
//     price: 1899,
//     stock: 3,
//     image: 'images/laptop-15.svg',
//     description: 'High-end portable gaming and creator machine. Excellent performance in a relatively compact form.',
//     tags: ['gaming', 'asus', 'premium']
//   }
// ];

// window.NE3XA.getProduct = function (id) {
//   return window.NE3XA.products.find(p => p.id === id) || null;
// };

// window.NE3XA.formatPrice = function (n) {
//   return '$' + Number(n).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
// };
